apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: pharma
  source:
    repoURL: https://github.com/kirandeget/zen-pharma-backend-lab1
    targetRevision: main
    path: auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
